# Generated by Django 5.2.7 on 2025-11-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("ingredients", models.JSONField(blank=True, default=list)),
                ("preparation_steps", models.TextField(max_length=255)),
                ("nutritional_info", models.JSONField(blank=True, default=dict)),
                (
                    "meal",
                    models.CharField(
                        choices=[("B", "Breakfast"), ("L", "Lunch"), ("D", "Dinner")],
                        max_length=1,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("G", "Gain Weight"),
                            ("L", "Lose Weight"),
                            ("N", "Nutrition"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Diet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("startDate", models.DateField(auto_now_add=True)),
                ("endDate", models.DateField()),
                (
                    "recipes",
                    models.ManyToManyField(
                        blank=True, related_name="diets", to="diets.recipe"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="tag",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="diets.tag"
            ),
        ),
    ]
