# Generated by Django 5.2.7 on 2025-11-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diets", "0002_diet_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="tag",
        ),
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="diets.tag"
            ),
        ),
    ]
