# Generated by Django 5.2.7 on 2025-11-10 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diets", "0004_remove_recipe_tags_recipe_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="tag",
            new_name="tags",
        ),
    ]
