# Generated by Django 5.2.7 on 2025-11-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diets", "0005_rename_tag_recipe_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="preparation_steps",
            field=models.TextField(max_length=500),
        ),
    ]
