# Generated by Django 5.2.7 on 2025-11-10 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diets", "0006_alter_recipe_preparation_steps"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diet",
            name="recipes",
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField()),
                (
                    "recipes",
                    models.ManyToManyField(
                        blank=True, related_name="meals", to="diets.recipe"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="diet",
            name="menus",
            field=models.ManyToManyField(
                blank=True, related_name="diets", to="diets.menu"
            ),
        ),
    ]
