# Generated by Django 5.2.7 on 2025-11-04 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ideal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("G", "Gain Weight"),
                            ("L", "Lose Weight"),
                            ("N", "Nutrition"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                (
                    "ideal_weight",
                    models.FloatField(
                        blank=True, help_text="Peso Ideal en kilogramos", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bmi", models.FloatField(help_text="Indice de Masa Corporal")),
                ("date_recorded", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Correo electrónico"
                    ),
                ),
                ("age", models.PositiveSmallIntegerField()),
                ("height", models.FloatField(help_text="Altura en centímetros")),
                ("weight", models.FloatField(help_text="Peso en kilogramos")),
                ("first_name", models.TextField(max_length=30)),
                ("last_name", models.TextField(max_length=30)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="users", to="diets.tag"
                    ),
                ),
                (
                    "ideal",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.ideal",
                    ),
                ),
                (
                    "progress",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.progress",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Historical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "diets",
                    models.ManyToManyField(
                        blank=True, related_name="historical_diets", to="diets.diet"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historicals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
