# Generated by Django 5.2.7 on 2025-11-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ideal",
            name="goal",
            field=models.CharField(
                choices=[
                    ("G", "Gain Weight"),
                    ("L", "Lose Weight"),
                    ("N", "Nutrition"),
                ],
                max_length=1,
            ),
        ),
    ]
