# Generated by Django 5.2.7 on 2025-11-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_ideal_goal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="progress",
            old_name="date_recorded",
            new_name="last_updated",
        ),
        migrations.RemoveField(
            model_name="historical",
            name="date",
        ),
        migrations.AddField(
            model_name="progress",
            name="current_height",
            field=models.FloatField(
                default=0.0, help_text="Altura actual en centímetros"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="progress",
            name="current_weight",
            field=models.FloatField(default=0.0, help_text="Peso actual en kilogramos"),
            preserve_default=False,
        ),
    ]
