# Generated by Django 5.2.7 on 2025-11-18 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_date_recorded_progress_last_updated_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Historical",
        ),
    ]
