# Generated by Django 5.2.7 on 2025-11-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_delete_historical"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_opt_out",
            field=models.BooleanField(
                default=False,
                help_text="If True, user will not receive broadcast/notification emails",
            ),
        ),
    ]
