# Generated by Django 5.2.7 on 2025-11-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_email_opt_out"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_opt_out",
            field=models.BooleanField(
                default=False,
                help_text="Si es True, el usuario no recibirá notificaciones por email",
                verbose_name="Email opt-out",
            ),
        ),
    ]
